# -*- coding: utf-8 -*-
"""siamese.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_FFxF7LmwVXXgwJUUX5EVYQizlQbfIF
"""

import models

# siamese network model which helps in one-shot learning

def siamese_network(input_dim_img,input_dim_aud):
    
    img_a = Input(shape=input_dim_img)
    img_b = Input(shape=input_dim_img)
    aud_a = Input(shape=input_dim_aud)
    aud_b = Input(shape=input_dim_aud)

    # extracting the image embeddings from the image network for two input images
    
    img_network = models.image_feat_network(input_dim_img)
    
    # load pretrained weights for image network
    img_network.load_weights(' set path ')

    img_network = Model(inputs = img_network.input , outputs = img_network.layers[-2].output)
    
    feat_img_a = img_network(img_a)
    feat_img_b = img_network(img_b)
    
    # extracting the audio embeddings from the image network for two output images

    aud_network = models.audio_feat_network(input_dim_aud)
    
    #load pretrained weights for audio network
    aud_network.load_weights(' set path ')

    aud_network = Model(inputs = aud_network.input , outputs = aud_network.layers[-2].output)

    feat_aud_a = aud_network(aud_a)
    feat_aud_b = aud_network(aud_b)
     

    # concatenate the first image's embeddings with the first audio's embeddings
    concat_a = Concatenate(axis=1)([feat_img_a, feat_aud_a])

    # concatenate the second image's embeddings with the second audio's embeddings
    concat_b = Concatenate(axis=1)([feat_img_b, feat_aud_b])

    input_dim = concat_a.shape[1] # (?) put the input dimensions here

    base_network = models.multimodal_network(input_dim)
    
    # left vector encodings
    encoded_l = base_network(concat_a) 
    # right vector encodings
    encoded_r = base_network(concat_b)

    # Layer to merge two encoded inputs with the l1 distance between them
    L1_layer = Lambda(lambda tensors:K.abs(tensors[0] - tensors[1]))

    # Get the L1 Distance between the two encoded legs and predict a sigmoid using that.
    L1_distance = L1_layer([encoded_l, encoded_r])
    prediction = Dense(1,activation='sigmoid')(L1_distance)

    model = Model(inputs=[img_a, aud_a, img_b,aud_b], outputs=prediction)

    optimizer = Adam(lr=1e-5, beta_1=0.9, beta_2=0.999)
    model.compile(loss="binary_crossentropy",optimizer=optimizer,metrics=['Precision'])

    return optimizer , model